### ISSUE TITLE
Extra std::memory_order_release?

### ISSUE THREAD

**Issue by StingX84** [rhashimoto/poolqueue#1]
Is `closed_.store` at `Promise.cpp:161` should really be `std::memory_order_release` ?? Maybe, `std::memory_order_relaxed` is just enough here, because this code is guarded by the mutex and mutex unlock has a release semantic?

Also, I have a question:
why did you closed the opportunity to use `void` as a return value to lambdas?

**Comment by rhashimoto** [comment]
Regarding requiring a return value, I found in my own usage of poolqueue that a common bug was forgetting to return a desired value from a lambda argument to `then()`, and you often don't discover that until runtime (some cases are found during compilation but not all). I weighed the benefit of finding those bugs at compile time as greater than the annoyance of having to return a value that just gets ignored.

I'll take a look at the memory flag. Thanks for bringing it to my attention!

**Comment by rhashimoto** [comment]
I took a look at the code, and I believe that memory ordering is correct as is. Although you are correct that [`Promise.cpp:161`](https://github.com/rhashimoto/poolqueue/blob/master/Promise.cpp#L161) is protected by the mutex, [`Promise.cpp:272`](https://github.com/rhashimoto/poolqueue/blob/master/Promise.cpp#L272) is not protected by the mutex _if_ `closed_` is `true`. Relaxing the ordering would leave a tiny window between `Promise.cpp:161` and the end of the mutex lock scope where `closed_` is `true` and accessing `downstream_` is unsynchronized.
